site_name: TEST Metadata Info
site_url: https://shallcro.github.io/md_test/
nav:
  - Home: index.md
  - Schema: schema/TEST_study_schema_v1.md
  - Style Guide: style/style_guide.md

theme:
  name: readthedocs
  prev_next_buttons_location: none
